//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerCheckpointed) DeepCopyInto(out *ContainerCheckpointed) {
	*out = *in
	in.CheckpointedAt.DeepCopyInto(&out.CheckpointedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerCheckpointed.
func (in *ContainerCheckpointed) DeepCopy() *ContainerCheckpointed {
	if in == nil {
		return nil
	}
	out := new(ContainerCheckpointed)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForensicSnapshot) DeepCopyInto(out *ForensicSnapshot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForensicSnapshot.
func (in *ForensicSnapshot) DeepCopy() *ForensicSnapshot {
	if in == nil {
		return nil
	}
	out := new(ForensicSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ForensicSnapshot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForensicSnapshotList) DeepCopyInto(out *ForensicSnapshotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ForensicSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForensicSnapshotList.
func (in *ForensicSnapshotList) DeepCopy() *ForensicSnapshotList {
	if in == nil {
		return nil
	}
	out := new(ForensicSnapshotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ForensicSnapshotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForensicSnapshotSpec) DeepCopyInto(out *ForensicSnapshotSpec) {
	*out = *in
	if in.ContainersCheckpointed != nil {
		in, out := &in.ContainersCheckpointed, &out.ContainersCheckpointed
		*out = make([]ContainerCheckpointed, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RequestedContainers != nil {
		in, out := &in.RequestedContainers, &out.RequestedContainers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Trigger = in.Trigger
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForensicSnapshotSpec.
func (in *ForensicSnapshotSpec) DeepCopy() *ForensicSnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(ForensicSnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForensicSnapshotStatus) DeepCopyInto(out *ForensicSnapshotStatus) {
	*out = *in
	in.CapturedAt.DeepCopyInto(&out.CapturedAt)
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	in.CompletedAt.DeepCopyInto(&out.CompletedAt)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForensicSnapshotStatus.
func (in *ForensicSnapshotStatus) DeepCopy() *ForensicSnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(ForensicSnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggerInfo) DeepCopyInto(out *TriggerInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggerInfo.
func (in *TriggerInfo) DeepCopy() *TriggerInfo {
	if in == nil {
		return nil
	}
	out := new(TriggerInfo)
	in.DeepCopyInto(out)
	return out
}
